# VoiceCommand Back-end

Back-end da aplicação de carrinho virtual controlado por voz. Recebe um arquivo de áudio via requisição HTTP, executa o pipeline de classificação localmente e retorna o comando reconhecido e a confiança da predição.

Desenvolvido com **FastAPI**, integrando um encoder **LSTM** para extração de features e um classificador **MLP** (sklearn Pipeline com scaler embutido).

---

## How It Works

```
Audio (WAV) → Feature Extraction (MFCC + spectral + onset + LSTM) → MLP Classifier → Command + Confidence
```

**Feature pipeline — 228 dimensions total:**
- MFCC + delta + delta² → 156 features
- Spectral features → 4 features
- Onset features → 4 features
- LSTM encoder output → 64 features

If the model confidence is **≤ 0.60**, the response returns `"desconhecido"` instead of a command, avoiding false activations from background noise.

---

## Required Files

The following files must be present in the project root before running:

```text
modelo_mlp_sem_chroma.pkl          # MLP Pipeline (includes internal StandardScaler)
label_encoder_mlp_sem_chroma.pkl   # Label encoder for class mapping
lstm_supervisionada_best.pt        # Trained LSTM encoder checkpoint
feature_extraction.py              # Feature extraction module
```

> The trained model files are generated by the training pipeline available at the [VoiceCommandTrainer](#) repository.

---

## Running

```bash
uvicorn api_voice:app --reload
```

---

## Endpoint

### `POST /predict`

Receives a WAV audio file and returns the classified voice command.

**Request**

| Field  | Type   | Description                             |
|--------|--------|-----------------------------------------|
| `file` | `File` | WAV audio file (mono, preferably 16kHz) |

**Response**

```json
{
  "command": "frente",
  "confidence": 0.87
}
```

If confidence is below the threshold:

```json
{
  "command": "desconhecido",
  "confidence": 0.43
}
```

**Supported commands:** `esquerda`, `direita`, `frente`, `tras`, `parar`

---

## Related Repositories

- 🧠 **Model training** — LSTM + MLP/SVM training pipeline
  [link do repositório de treinamento]

- 🖥️ **Front-end** — Virtual car interface and visualization
  [github.com/uSilas/projeto_reconhecimento_padroes](https://github.com/uSilas/projeto_reconhecimento_padroes)
